version: "3.9"

services:
  python-app:
    build: .
    container_name: python_gui_app
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /tmp/.docker.xauth:/tmp/.docker.xauth
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/tmp/.docker.xauth
    devices:
      - /dev/dri:/dev/dri
    network_mode: "host"
    tty: true
    command: /bin/bash -c "chmod -R 777 /app && /bin/bash"

